Update code to use latest tfenv 3.0.0 release

diff --git a/bin/tfenv b/bin/tfenv
--- a/bin/tfenv
+++ b/bin/tfenv
@@ -17,16 +17,17 @@ if [ -z "${TGENV_ROOT:-""}" ]; then
     local file_name;
 
     while [ "${target_file}" != "" ]; do
-      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TGENV_ROOT";
-      file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine TGENV_ROOT";
+      cd "${target_file%/*}" || early_death "Failed to 'cd \$(${target_file%/*})' while trying to determine TGENV_ROOT";
+      file_name="${target_file##*/}" || early_death "Failed to '\"${target_file##*/}\"' while trying to determine TGENV_ROOT";
       target_file="$(readlink "${file_name}")";
     done;
 
     echo "$(pwd -P)/${file_name}";
   };
+  TGENV_SHIM=$(readlink_f "${0}")
+  TGENV_ROOT="${TGENV_SHIM%/*/*}";
+  [ -n "${TGENV_ROOT}" ] || early_death "Failed to determine TGENV_ROOT";
 
-  TGENV_ROOT="$(cd "$(dirname "$(readlink_f "${0}")")/.." && pwd)";
-  [ -n ${TGENV_ROOT} ] || early_death "Failed to 'cd \"\$(dirname \"\$(readlink_f \"${0}\")\")/..\" && pwd' while trying to determine TGENV_ROOT";
 else
   TGENV_ROOT="${TGENV_ROOT%/}";
 fi;
@@ -35,7 +36,7 @@ export TGENV_ROOT;
 if [ -n "${TGENV_HELPERS:-""}" ]; then
   log 'debug' 'TGENV_HELPERS is set, not sourcing helpers again';
 else
-  [ "${TGENV_DEBUG:-0}" -gt 0 ] && echo "[DEBUG] Sourcing helpers from ${TGENV_ROOT}/lib/helpers.sh";
+  [ "${TGENV_DEBUG:-0}" -gt 0 ] && >&2 echo "[DEBUG] Sourcing helpers from ${TGENV_ROOT}/lib/helpers.sh";
   if source "${TGENV_ROOT}/lib/helpers.sh"; then
     log 'debug' 'Helpers sourced successfully';
   else
@@ -61,7 +62,7 @@ done;
 declare arg="${1:-""}";
 
 log 'debug' "Setting TGENV_DIR to ${PWD}";
-export TGENV_DIR="${PWD}"
+export TGENV_DIR="${PWD}";
 
 abort() {
   log 'debug' 'Aborting...';
diff --git a/libexec/tgenv-install b/libexec/tgenv-install
--- a/libexec/tgenv-install
+++ b/libexec/tgenv-install
@@ -63,7 +63,8 @@ done;
 declare requested="${1:-""}";
 
 log debug "Resolving version with: tgenv-resolve-version ${requested}";
-declare resolved="$(tgenv-resolve-version ${requested})";
+declare resolved;
+resolved="$(tgenv-resolve-version ${requested})" || log 'error' "Failed to resolve ${requested} version";
 
 declare version="${resolved%%\:*}";
 declare regex="${resolved##*\:}";
@@ -72,16 +73,37 @@ declare regex="${resolved##*\:}";
 
 log 'debug' "Processing install for version ${version}, using regex ${regex}";
 
-version="$(tgenv-list-remote | grep -e "${regex}" | head -n 1)";
-[ -n "${version}" ] || log 'error' "No versions matching '${requested}' found in remote";
+remote_version="$(tgenv-list-remote | grep -e "${regex}" | head -n 1)";
+[ -n "${remote_version}" ] && version="${remote_version}" || log 'error' "No versions matching '${requested:-$version}' found in remote";
 
-dst_path="${TGENV_ROOT}/versions/${version}";
+dst_path="${TGENV_CONFIG_DIR}/versions/${version}";
 if [ -f "${dst_path}/terragrunt" ]; then
-  echo "Terraform v${version} is already installed";
+  echo "Terragrunt v${version} is already installed";
   exit 0;
 fi;
 
-TGENV_ARCH="${TGENV_ARCH:-amd64}";
+TGENV_ARCH="${TGENV_ARCH:-amd64}"; # Add support of ARM64 for Linux & Apple Silicon
+# case "$(uname -m)" in
+#   aarch64* | arm64*)
+#     # There is no arm64 support for versions:
+#     # < 0.11.15
+#     # >= 0.12.0, < 0.12.30
+#     # >= 0.13.0, < 0.13.5
+#     if [[ "${version}" =~ 0\.(([0-9]|10))\.\d* ||
+#           "${version}" =~ 0\.11\.(([0-9]|1[0-4]))$ ||
+#           "${version}" =~ 0\.12\.(([0-9]|[1-2][0-9]))$ ||
+#           "${version}" =~ 0\.13\.[0-4]$
+#     ]]; then
+#       TGENV_ARCH="${TGENV_ARCH:-amd64}";
+#     else
+#       TGENV_ARCH="${TGENV_ARCH:-arm64}";
+#     fi;
+#     ;;
+#   *)
+#     TGENV_ARCH="${TGENV_ARCH:-amd64}";
+#     ;;
+# esac;
+
 case "$(uname -s)" in
   Darwin*)
     os="darwin_${TGENV_ARCH}";
@@ -96,7 +118,7 @@ case "$(uname -s)" in
     os="windows_${TGENV_ARCH}";
     ;;
   FreeBSD*)
-    os="freebsd_${TGENV_ARCH}"
+    os="freebsd_${TGENV_ARCH}";
     ;;
   *)
     os="linux_${TGENV_ARCH}";
@@ -110,16 +132,30 @@ sha256sum_bin="$(command -v sha256sum 2>/dev/null)";
 TGENV_REMOTE="${TGENV_REMOTE:-https://github.com/gruntwork-io}";
 version_url="${TGENV_REMOTE}/terragrunt/releases/download/v${version}";
 
-tarball_name="terragrunt_${os}";
+tarball_name="terragrunt_${os}"; # Thanks for the inconsistency in 0.12-alpha, Hashicorp(!)
+# if [[ "${version}" =~ 0.12.0-alpha[3-9] ]]; then
+#   tarball_name="terragrunt_${version}_terragrunt_${version}_${os}.zip";
+# else
+#   tarball_name="terragrunt_${version}_${os}.zip";
+# fi;
 
-# shasums_name="terragrunt_${version}_SHA256SUMS";
+shasums_name="SHA256SUMS";
+# shasums_signing_key_postfix=".72D7468F";
+# shasums_sig="${shasums_name}${shasums_signing_key_postfix}.sig";
 
-log 'info' "Installing Terraform v${version}";
+log 'info' "Installing Terragrunt v${version}";
 
-# # Create a local temporary directory for downloads
-# download_tmp="$(mktemp -d tgenv_download.XXXXXX)" || log 'error' "Unable to create temporary download directory in $(pwd)";
-# # Clean it up in case of error
-# trap "rm -rf ${download_tmp}" EXIT;
+# Create a local temporary directory for downloads
+tmpdir_arg="-t";
+
+if mktemp --help 2>&1 | grep -- '--tmpdir' >/dev/null; then
+  tmpdir_arg="--tmpdir";
+fi;
+
+download_tmp="$(mktemp -d ${tmpdir_arg} tgenv_download.XXXXXX)" || log 'error' "Unable to create temporary download directory (mktemp -d ${tmpdir_arg} tgenv_download.XXXXXX). Working Directory is: $(pwd)";
+
+# Clean it up in case of error
+trap "rm -rf ${download_tmp}" EXIT;
 
 declare curl_progress="";
 case "${TGENV_CURL_OUTPUT:-2}" in
@@ -140,26 +176,66 @@ case "${TGENV_CURL_OUTPUT:-2}" in
     ;;
 esac;
 
-mkdir -p "${dst_path}" || log 'error' "Failed to make directory ${dst_path}";
 log 'info' "Downloading release tarball from ${version_url}/${tarball_name}";
-# curlw ${curl_progress} -f -o "${dst_path}/terragrunt" "${version_url}/${tarball_name}" || log 'error' 'Tarball download failed';
-curlw ${curl_progress} --location-trusted -f -o "${dst_path}/terragrunt" "${version_url}/${tarball_name}" || log 'error' 'Tarball download failed';
-chmod +x "${dst_path}/terragrunt"
-
-# log 'info' "Downloading SHA hash file from ${version_url}/${shasums_name}";
-# curlw -s -f -o "${download_tmp}/${shasums_name}" "${version_url}/${shasums_name}" || log 'error' 'SHA256 hashes download failed';
+curlw ${curl_progress} -f -L -o "${download_tmp}/${tarball_name}" "${version_url}/${tarball_name}" || log 'error' 'Tarball download failed';
+log 'info' "Downloading SHA hash file from ${version_url}/${shasums_name}";
+curlw -s -f -L -o "${download_tmp}/${shasums_name}" "${version_url}/${shasums_name}" || log 'error' 'SHA256 hashes download failed';
 
 # download_signature() {
-#   log 'info' "Downloading SHA hash signature file from ${version_url}/${shasums_name}.sig";
-#   curlw -s -f \
-#     -o "${download_tmp}/${shasums_name}.sig" \
-#     "${version_url}/${shasums_name}.sig" \
-#     && log 'debug' "SHA256SUMS signature file downloaded successfully to ${download_tmp}/${shasums_name}.sig" \
+#   log 'info' "Downloading SHA hash signature file from ${version_url}/${shasums_sig}";
+#   curlw -s -f -L \
+#     -o "${download_tmp}/${shasums_sig}" \
+#     "${version_url}/${shasums_sig}" \
+#     && log 'debug' "SHA256SUMS signature file downloaded successfully to ${download_tmp}/${shasums_sig}" \
 #     || log 'error' 'SHA256SUMS signature download failed';
 # };
 
-# # Verify signature if verification mechanism (keybase, gpg, etc) is present
-# if [[ -n "${keybase_bin}" && -x "${keybase_bin}" ]]; then
+# If on MacOS with Homebrew, use GNU grep
+# This allows keybase login detection to work on Mac,
+# and is required to be able to detect terragrunt version
+# from "required_version" setting in "*.tf" files
+check_dependencies;
+
+# Verify signature if verification mechanism (keybase, gpg, etc) is present
+# if [[ -f "${TGENV_CONFIG_DIR}/use-gnupg" ]]; then
+#   # GnuPG uses the user's keyring, and any web-of-trust or local signatures or
+#   # anything else they have setup.  This is the crazy-powerful mode which is
+#   # overly confusing to newcomers.  We don't support it without the user creating
+#   # the file use-gnupg, optionally with directives in it.
+#   gnupg_command="$(sed -E -n -e 's/^binary: *//p' <"${TGENV_CONFIG_DIR}/use-gnupg")";
+#   [[ -n "${gnupg_command}" ]] || gnupg_command=gpg;
+
+#   download_signature;
+#   # Deliberately unquoted command, in case caller has something fancier in "use-gnupg".
+#   # Also, don't use batch mode.  If someone specifies GnuPG, let them deal with any prompting.
+#   ${gnupg_command} \
+#     --verify "${download_tmp}/${shasums_sig}" \
+#     "${download_tmp}/${shasums_name}" \
+#     || log 'error' 'PGP signature rejected by GnuPG';
+
+# elif [[ -f "${TGENV_CONFIG_DIR}/use-gpgv" ]]; then
+#   # gpgv is a much simpler interface to verification, but does require that the
+#   # key have been downloaded and marked trusted.
+#   # We don't force the caller to trust the tgenv repo's copy of their key, they
+#   # have to choose to make that trust decision.
+#   gpgv_command="$(sed -E -n -e 's/^binary: *//p' <"${TGENV_CONFIG_DIR}/use-gpgv")";
+#   trust_tgenv="$(sed -E -n -e 's/^trust.?tgenv: *//p' <"${TGENV_CONFIG_DIR}/use-gpgv")";
+#   [[ -n "${gpgv_command}" ]] || gpgv_command=gpgv;
+
+#   download_signature;
+#   if [[ "${trust_tgenv}" == 'yes' ]]; then
+#     ${gpgv_command} \
+#       --keyring "${TGENV_ROOT}/share/hashicorp-keys.pgp" \
+#       "${download_tmp}/${shasums_sig}" \
+#       "${download_tmp}/${shasums_name}" \
+#       || log 'error' 'PGP signature rejected';
+#   else
+#     ${gpgv_command} \
+#       "${download_tmp}/${shasums_sig}" \
+#       "${download_tmp}/${shasums_name}" \
+#       || log 'error' 'PGP signature rejected';
+#   fi;
+# elif [[ -n "${keybase_bin}" && -x "${keybase_bin}" ]]; then
 #   grep -Eq '^Logged in:[[:space:]]*yes' <("${keybase_bin}" status);
 #   keybase_logged_in="${?}";
 #   grep -Fq hashicorp <("${keybase_bin}" list-following);
@@ -171,53 +247,14 @@ chmod +x "${dst_path}/terragrunt"
 #     download_signature;
 #     "${keybase_bin}" pgp verify \
 #       -S hashicorp \
-#       -d "${download_tmp}/${shasums_name}.sig" \
+#       -d "${download_tmp}/${shasums_sig}" \
 #       -i "${download_tmp}/${shasums_name}" \
 #       && log 'debug' 'SHA256SUMS signature matched' \
 #       || log 'error' 'SHA256SUMS signature does not match!';
 #   fi;
-
-# elif [[ -f "${TGENV_ROOT}/use-gnupg" ]]; then
-#   # GnuPG uses the user's keyring, and any web-of-trust or local signatures or
-#   # anything else they have setup.  This is the crazy-powerful mode which is
-#   # overly confusing to newcomers.  We don't support it without the user creating
-#   # the file use-gnupg, optionally with directives in it.
-#   gnupg_command="$(sed -E -n -e 's/^binary: *//p' <"${TGENV_ROOT}/use-gnupg")";
-#   [[ -n "${gnupg_command}" ]] || gnupg_command=gpg;
-
-#   download_signature;
-#   # Deliberately unquoted command, in case caller has something fancier in "use-gnupg".
-#   # Also, don't use batch mode.  If someone specifies GnuPG, let them deal with any prompting.
-#   ${gnupg_command} \
-#     --verify "${download_tmp}/${shasums_name}.sig" \
-#     "${download_tmp}/${shasums_name}" \
-#     || log 'error' 'PGP signature rejected by GnuPG';
-
-# elif [[ -f "${TGENV_ROOT}/use-gpgv" ]]; then
-#   # gpgv is a much simpler interface to verification, but does require that the
-#   # key have been downloaded and marked trusted.
-#   # We don't force the caller to trust the tgenv repo's copy of their key, they
-#   # have to choose to make that trust decision.
-#   gpgv_command="$(sed -E -n -e 's/^binary: *//p' <"${TGENV_ROOT}/use-gpgv")";
-#   trust_tgenv="$(sed -E -n -e 's/^trust.?tgenv: *//p' <"${TGENV_ROOT}/use-gpgv")";
-#   [[ -n "${gpgv_command}" ]] || gpgv_command=gpgv;
-
-#   download_signature;
-#   if [[ "${trust_tgenv}" == 'yes' ]]; then
-#     ${gpgv_command} \
-#       --keyring "${TGENV_ROOT}/share/hashicorp-keys.pgp" \
-#       "${download_tmp}/${shasums_name}.sig" \
-#       "${download_tmp}/${shasums_name}" \
-#       || log 'error' 'PGP signature rejected';
-#   else
-#     ${gpgv_command} \
-#       "${download_tmp}/${shasums_name}.sig" \
-#       "${download_tmp}/${shasums_name}" \
-#       || log 'error' 'PGP signature rejected';
-#   fi;
 # else
 #   # Warning about this avoids an unwarranted sense of confidence in the SHA check
-#   log 'warn' 'No keybase install found, skipping OpenPGP signature verification';
+#   log 'warn' "Not instructed to use Local PGP (${TGENV_CONFIG_DIR}/use-{gpgv,gnupg}) & No keybase install found, skipping OpenPGP signature verification";
 # fi;
 
 # if [[ -n "${shasum_bin}" && -x "${shasum_bin}" ]]; then
@@ -226,24 +263,22 @@ chmod +x "${dst_path}/terragrunt"
 #     "${shasum_bin}" \
 #       -a 256 \
 #       -s \
-#       -c <(grep -F "${tarball_name}" "${shasums_name}") \
-#       || log 'error' 'SHA256 hash does not match!';
-#   );
+#       -c <(grep -F "${tarball_name}" "${shasums_name}")
+#   ) || log 'error' 'SHA256 hash does not match!';
 # elif [[ -n "${sha256sum_bin}" && -x "${sha256sum_bin}" ]]; then
 #   (
 #     cd "${download_tmp}";
 #     "${sha256sum_bin}" \
-#       -c <(grep -F "${tarball_name}" "${shasums_name}") \
-#       || log 'error' 'SHA256 hash does not match!';
-#   );
+#       -c <(grep -F "${tarball_name}" "${shasums_name}")
+#   ) || log 'error' 'SHA256 hash does not match!';
 # else
 #   # Lack of shasum deserves a proper warning
 #   log 'warn' 'No shasum tool available. Skipping SHA256 hash validation';
 # fi;
 
-# mkdir -p "${dst_path}" || log 'error' "Failed to make directory ${dst_path}";
+mkdir -p "${dst_path}" || log 'error' "Failed to make directory ${dst_path}";
 
-# declare unzip_output;
+cp ${download_tmp}/${tarball_name} ${dst_path}/terragrunt ; chmod +x ${dst_path}/terragrunt # declare unzip_output;
 # unzip_output="$(unzip -o "${download_tmp}/${tarball_name}" -d "${dst_path}")" || log 'error' 'Tarball unzip failed';
 # while IFS= read -r unzip_line; do
 #  log 'info' "${unzip_line}";
diff --git a/libexec/tgenv-list b/libexec/tgenv-list
--- a/libexec/tgenv-list
+++ b/libexec/tgenv-list
@@ -60,34 +60,41 @@ done;
 #####################
 
 [ "${#}" -ne 0 ] \
-  && log 'error' "usage: tgenv list"
+  && log 'error' "usage: tgenv list";
 
-[ -d "${TGENV_ROOT}/versions" ] \
-  || log 'error' 'No versions available. Please install one with: tgenv install'
+[ -d "${TGENV_CONFIG_DIR}/versions" ] \
+  || log 'error' 'No versions available. Please install one with: tgenv install';
 
-[[ -x "${TGENV_ROOT}/versions" && -r "${TGENV_ROOT}/versions" ]] \
-  || log 'error' "tgenv versions directory is inaccessible: ${TGENV_ROOT}/versions";
+[[ -x "${TGENV_CONFIG_DIR}/versions" && -r "${TGENV_CONFIG_DIR}/versions" ]] \
+  || log 'error' "tgenv versions directory is inaccessible: ${TGENV_CONFIG_DIR}/versions";
 
-version_name="$(tgenv-version-name)" \
-  && log 'debug' "tgenv-version-name reported: ${version_name}" \
-  || log 'error' "tgenv-version-name failed";
+version_name="$(tgenv-version-name 2>/dev/null || true)" \
+  && log 'debug' "tgenv-version-name reported: ${version_name}";
 export version_name;
 
-version_file="$(tgenv-version-file)" \
-  && log 'debug' "tgenv-version-file reported: ${version_file}" \
-  || log 'error' "tgenv-version-file failed";
-export version_file;
+if [ -z "${TGENV_TERRAGRUNT_VERSION:-""}" ]; then
+  version_source="$(tgenv-version-file)" \
+    && log 'debug' "tgenv-version-file reported: ${version_source}" \
+    || log 'error' "tgenv-version-file failed";
+else
+  version_source='TGENV_TERRAGRUNT_VERSION';
+fi;
+export version_source;
+
+# Register for whether a default terragrunt version has yet been set
+declare -i default_set=0;
 
 print_version () {
   if [ "${1}" == "${version_name}" ]; then
-    echo "* ${1} (set by ${version_file})";
+    echo "* ${1} (set by ${version_source})";
+    default_set=1;
   else
     echo "  ${1}";
   fi;
 };
 
 log 'debug' 'Listing versions...';
-local_versions=($(\find "${TGENV_ROOT}/versions" -type d -exec basename {} \; \
+local_versions=($(\find "${TGENV_CONFIG_DIR}/versions/" -type d -exec basename {} \; \
   | tail -n +2 \
   | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3));
 
@@ -97,3 +104,7 @@ log 'debug' 'Printing versions...';
 for local_version in ${local_versions[@]}; do
   print_version "${local_version}";
 done;
+
+[ "${default_set}" -eq 0 ] && log 'info' "No default set. Set with 'tgenv use <version>'";
+
+exit 0;
diff --git a/libexec/tgenv-pin b/libexec/tgenv-pin
--- a/libexec/tgenv-pin
+++ b/libexec/tgenv-pin
@@ -18,7 +18,7 @@ if [ -z "${TGENV_ROOT:-""}" ]; then
     local file_name;
 
     while [ "${target_file}" != "" ]; do
-      cd "$(dirname "${target_file}")" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TGENV_ROOT";
+      cd "$(dirname ${target_file})" || early_death "Failed to 'cd \$(dirname ${target_file})' while trying to determine TGENV_ROOT";
       file_name="$(basename "${target_file}")" || early_death "Failed to 'basename \"${target_file}\"' while trying to determine TGENV_ROOT";
       target_file="$(readlink "${file_name}")";
     done;
@@ -58,18 +58,20 @@ done;
 #####################
 # Begin Script Body #
 #####################
-if [ ${#} -ne 0 ];then
-  echo "usage: tgenv list-remote" 1>&2
-  exit 1
-fi
 
-link_release="https://api.github.com/repos/gruntwork-io/terragrunt/tags?per_page=1000"
-print=$(curl -sf $link_release)
+[ "${#}" -ne 0 ] \
+  && log 'error' "usage: tgenv pin";
 
-return_code=$?
-if [ $return_code -eq 22 ];then
-  log 'error' "Failed to get list verion on $link_release"
-  print=`cat ${TGENV_ROOT}/list_all_versions_offline`
-fi
+[ -d "${TGENV_CONFIG_DIR}/versions/" ] \
+  || log 'error' 'No versions available. Please install one with: tgenv install';
 
-echo $print | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta)[0-9]+)?" | uniq
+[[ -x "${TGENV_CONFIG_DIR}/versions" && -r "${TGENV_CONFIG_DIR}/versions" ]] \
+  || log 'error' "tgenv versions directory is inaccessible: ${TGENV_CONFIG_DIR}/versions";
+
+version_name="$(tgenv-version-name 2>/dev/null || true)" \
+  && log 'debug' "tgenv-version-name reported: ${version_name}";
+
+echo "${version_name}" > .terragrunt-version;
+log 'info' "Pinned version by writing \"${version_name}\" to $(pwd)/.terragrunt-version";
+
+exit 0;
diff --git a/libexec/tgenv-use b/libexec/tgenv-use
--- a/libexec/tgenv-use
+++ b/libexec/tgenv-use
@@ -60,45 +60,95 @@ done;
 
 [ "${#}" -gt 1 ] && log 'error' 'usage: tgenv use [<version>]';
 
-[ -d "${TGENV_ROOT}/versions" ] \
-  || log 'error' 'No versions of terragrunt installed. Please install one with: tgenv install';
+declare auto_install="${TGENV_AUTO_INSTALL:-true}";
 
-declare requested="${1:-""}";
+if [ "${auto_install}" != 'true' ]; then
+  [ -d "${TGENV_CONFIG_DIR}/versions" ] \
+    || log 'error' 'No versions of terragrunt installed. Please install one with: tgenv install';
+fi;
 
-log debug "Resolving version with: tgenv-resolve-version ${requested}";
-declare resolved="$(tgenv-resolve-version ${requested})";
+declare requested_arg="${1:-""}";
+declare version_source_suffix="";
+declare requested="${requested_arg}";
+declare loaded_version_file="$(tgenv-version-file)";
+
+if [ -z "${requested_arg}" -a -z "${TGENV_TERRAGRUNT_VERSION:-""}" ]; then
+  version_source_suffix=" (set by ${loaded_version_file})";
+
+  if [ -f "${loaded_version_file}" ]; then
+    requested="$(cat "${loaded_version_file}" || true)";
+  else
+    # No-one asked for anything, no default version is set either
+    requested='latest';
+  fi;
+
+elif [ -z "${requested_arg}" ]; then
+  version_source_suffix=' (set by TGENV_TERRAGRUNT_VERSION)';
+  requested="${TGENV_TERRAGRUNT_VERSION}";
+fi;
+
+log debug "Resolving version with: tgenv-resolve-version ${requested_arg}";
+declare resolved="$(tgenv-resolve-version ${requested_arg})";
+[ -z "${resolved}" ] && log 'error' "Failure to resolve version from ${requested_arg}";
+
+log debug "Resolved to: ${resolved}";
 
 declare version="${resolved%%\:*}";
 declare regex="${resolved##*\:}";
+declare installed_version='';
 
-log 'debug' "Searching ${TGENV_ROOT}/versions for latest version matching ${regex}";
-declare version="$(\find "${TGENV_ROOT}/versions" -type d -exec basename {} \; \
-  | tail -n +2 \
-  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
-  | grep -e "${regex}" \
-  | head -n 1
-)";
+log 'debug' "Searching ${TGENV_CONFIG_DIR}/versions/ for latest version matching ${regex}";
 
-[ -n "${version}" ] \
-  && log 'debug' "Found version: ${version}" \
-  || log 'error' "No installed versions of terragrunt matched '${1}'";
-
-target_path="${TGENV_ROOT}/versions/${version}";
-[ -f "${target_path}/terragrunt" ] \
-  || log 'error' "Version directory for ${version} is present, but the terragrunt binary is not! Manual intervention required.";
-[ -x "${target_path}/terragrunt" ] \
-  || log 'error' "Version directory for ${version} is present, but the terragrunt binary is not executable! Manual intervention required.";
-
-log 'info' "Switching default version to v${version}";
-version_file="${TGENV_ROOT}/version";
-log 'debug' "Writing \"${version}\" to \"${version_file}\"";
-echo "${version}" > "${version_file}" \
-  || log 'error' "Switch to v${version} failed";
-
-if [ "${version_file}" != "$(tgenv-version-file)" ]; then
-  log 'warn' "Default version file overridden by $(tgenv-version-file), changing the default version has no effect";
+if [ -d "${TGENV_CONFIG_DIR}/versions" ]; then
+  installed_version="$(\find "${TGENV_CONFIG_DIR}/versions/" -type d -exec basename {} \; \
+    | tail -n +2 \
+    | grep -e "${regex}" \
+    | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3r,3 \
+    | head -n 1
+  )";
 fi;
 
-terragrunt --version 1>/dev/null \
-  || log 'error' "'terragrunt --version' failed. Something is seriously wrong";
-log 'info' "Switching completed";
+if [ -n "${installed_version}" ]; then
+  log 'debug' "Found version: ${installed_version}";
+else
+  if [ "${auto_install}" == 'true' ]; then
+    log 'info' "No installed versions of terragrunt matched '${resolved}'. Trying to install a matching version since TGENV_AUTO_INSTALL=true";
+
+    declare install_version='';
+    [ "${version}" == 'latest' ] && install_version="${version}:${regex}" || install_version="${version}";
+
+    tgenv-install "${install_version}" || log 'error' 'Installing a matching version failed';
+
+    installed_version="$(\find "${TGENV_CONFIG_DIR}/versions/" -type d -exec basename {} \; \
+      | tail -n +2 \
+      | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
+      | grep -e "${regex}" \
+      | head -n 1
+    )";
+
+    [ -n "${installed_version}" ] \
+      || log 'error' "Despite successfully installing a version matching '${resolved}', a matching version could not be found in '${TGENV_CONFIG_DIR}/versions/' - This should be pretty much impossible";
+  fi;
+fi;
+
+target_path="${TGENV_CONFIG_DIR}/versions/${installed_version}";
+log 'debug' "target_path is ${TGENV_CONFIG_DIR}/versions/${installed_version}";
+
+[ -d "${target_path}" ] \
+  || log 'error' "Version directory for ${installed_version} (${target_path}) is not present! Manual intervention required.";
+[ -f "${target_path}/terragrunt" ] \
+  || log 'error' "Version directory for ${installed_version} is present, but the terragrunt binary is not! Manual intervention required.";
+[ -x "${target_path}/terragrunt" ] \
+  || log 'error' "Version directory for ${installed_version} is present, but the terragrunt binary is not executable! Manual intervention required.";
+
+log 'info' "Switching default version to v${installed_version}";
+version_file="${TGENV_CONFIG_DIR}/version";
+log 'debug' "Writing \"${installed_version}\" to \"${version_file}\"";
+echo "${installed_version}" > "${version_file}" \
+  || log 'error' "Switch to v${installed_version} failed";
+
+if [ "${version_file}" != "${loaded_version_file}" ]; then
+  log 'warn' "Default version file overridden by ${loaded_version_file}, changing the default version has no effect";
+fi;
+
+log 'info' "Default version (when not overridden by .terragrunt-version or TGENV_TERRAGRUNT_VERSION) is now: ${installed_version}";
