Implement caching of remote versions

diff --git a/libexec/tgenv-list-remote b/libexec/tgenv-list-remote
--- a/libexec/tgenv-list-remote
+++ b/libexec/tgenv-list-remote
@@ -63,16 +63,32 @@ if [ ${#} -ne 0 ];then
   exit 1
 fi
 
+today=$(date +"%Y-%m-%d")
 link_release="https://api.github.com/repos/gruntwork-io/terragrunt/tags?per_page=1000"
 
-print=$(curl -sf $link_release -o /tmp/list_all_versions_offline ; cat /tmp/list_all_versions_offline)
+if [ ! -d ${TGENV_ROOT}/cache ]
+then
+    mkdir -p ${TGENV_ROOT}/cache
+fi
 
-return_code=$?
-if [ $return_code -eq 22 ];then
-  log 'error' "Failed to get list version on $link_release"
-  print=`cat ${TGENV_ROOT}/list_all_versions_offline`
+if [ -f ${TGENV_ROOT}/cache/list_remote_${today} ]
+then
+  log 'debug' 'Using cached list of terragrunt versions...';
+  echo "Using today's cached list of terragrunt versions... delete ${TGENV_ROOT}/cache to force downloading full list from github."
+  print=`cat ${TGENV_ROOT}/cache/list_remote_${today}`
 else
-  cp /tmp/list_all_versions_offline "${TGENV_ROOT}/list_all_versions_offline"
+  log 'debug' 'Cached list of terragrunt versions does not exists, Pulling from github API and saving to cache...'
+  curl -sf $link_release -o ${TGENV_ROOT}/cache/list_remote_${today}
+  
+  return_code=$?
+  if [ $return_code -eq 22 ];then
+    log 'error' "Failed to get list of terragrunt version on $link_release. Using the most recent list from cache..."
+
+    most_recent_cache_list_version=$(ls ${TGENV_ROOT}/cache | tr "" "\n" | tail -1)
+    print=$(cat ${TGENV_ROOT}/cache/${most_recent_cache_list_version})
+  else
+    print=$(cat ${TGENV_ROOT}/cache/list_remote_${today})
+  fi
 fi
 
 echo $print | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(rc|beta)[0-9]+)?" | uniq
